# Generated by Django 3.0.2 on 2020-02-17 17:29

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matchday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('season', models.IntegerField(help_text='Season')),
                ('matchday', models.IntegerField(help_text='matchday')),
            ],
            options={
                'unique_together': {('season', 'matchday')},
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Club Name', max_length=200)),
                ('cid', models.TextField(help_text='Club Id', max_length=8)),
            ],
            options={
                'unique_together': {('cid',)},
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(help_text='USER ID')),
                ('name', models.TextField(help_text='Players Sur Name', max_length=200)),
                ('pid', models.IntegerField(help_text='Players Id')),
                ('kader', models.BooleanField(help_text='Is in Kader')),
                ('averagePoints', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average Points Season per Game', max_digits=4)),
                ('actualPoints', models.IntegerField(default=0, help_text='Actual Points Season')),
                ('lastPoints', models.IntegerField(default=0, help_text='Points last game')),
                ('currentPoints', models.IntegerField(default=0, help_text='Current Game Points')),
                ('currentRating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current Game Rating', max_digits=4)),
                ('last_update', models.DateField(auto_now=True)),
                ('mdid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crawler.Matchday')),
            ],
            options={
                'unique_together': {('mdid', 'pid', 'userId')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField(help_text='Match Id')),
                ('begin', models.DateTimeField()),
                ('home', models.TextField(help_text='Home Club Id', max_length=8)),
                ('away', models.TextField(help_text='Away Club Id', max_length=8)),
                ('currentResult', models.TextField(help_text='Result', max_length=10)),
                ('mdid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crawler.Matchday')),
            ],
            options={
                'unique_together': {('mid', 'mdid')},
            },
        ),
    ]
