# Generated by Django 3.0.2 on 2020-02-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Human Name', max_length=200)),
                ('uid', models.IntegerField(help_text='Human Id', max_length=8)),
            ],
            options={
                'unique_together': {('uid',)},
            },
        ),
    ]
