# Generated by Django 3.0.2 on 2020-03-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_player_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='lastPoints',
            field=models.IntegerField(default=0, help_text='User Points last game'),
        ),
        migrations.AddField(
            model_name='users',
            name='livePoints',
            field=models.IntegerField(default=0, help_text='User Live Points'),
        ),
        migrations.AddField(
            model_name='users',
            name='totalPoints',
            field=models.IntegerField(default=0, help_text='User Points season'),
        ),
    ]
